version: "3"
services:
  web_server:
    container_name: web_server
    image: "nginx:alpine"
    ports:
      - "8080:80"
    volumes:
      - "${INSTALL_PATH}/web/src/mydh/html:/usr/share/nginx/html:ro"
      # - "${INSTALL_PATH}/web/conf/nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - app_server
  app_server:
    container_name: app_server
    image: "node:16"
    environment:
      - RUNNING_MODE=rest
      - HTTPS=true
      - PORT=9550
      - MONGODB=mongodb://mydhdb:27017/mydh
      - MQ=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@mydhmq
      - AppId=${WECHAT_APP_ID}
      - AppSecret=${WECHAT_APP_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - SessionExpiresIn=${SESSION_EXPIRES_IN}
      - CERT_PRI_KEY_PATH:${INSTALL_PATH}/cert/.acme.sh/mygdh.top_ecc/mygdh.top.key
      - CERT_FULL_CHAIN_PATH:${INSTALL_PATH}/cert/.acme.sh/mygdh.top_ecc/fullchain.cer
    entrypoint:
      - "sh"
      - "-c"
      - "npm install && node server.js"
    ports:
      - "443:9550"
      - "80:9550"
    working_dir: "/app"
    volumes:
      - "${INSTALL_PATH}/app/src/mydh/buddhists:/app"
      - "${INSTALL_PATH}/cert/.acme.sh/mygdh.top_ecc/mygdh.top.key:/app/.cert/privkey.pem:ro"
      - "${INSTALL_PATH}/cert/.acme.sh/mygdh.top_ecc/fullchain.cer:/app/.cert/fullchain.pem:ro"
    depends_on:
      - rabbitmq
      - mongodb
    links:
      - mongodb:mydhdb
      - rabbitmq:mydhmq
  rabbitmq:
    container_name: "rabbitmq"
    image: "rabbitmq:3-management-alpine"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672"
      - "15672"
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ${INSTALL_PATH}/db/mongo/data/mydh:/data/db
      - ${INSTALL_PATH}/db/mongo/backup/mydh:/backups
    ports:
      - "28517:27017"
