version: "3"
services:
  bigcity_rabbitmq:
    container_name: bigcity_rabbitmq
    image: "rabbitmq:management"
    environment:
      - RABBITMQ_DEFAULT_USER=jsm
      - RABBITMQ_DEFAULT_PASS=jsm
    ports:
      - "5672:5672"
      - "15672:15672"
  bigcity_mongodb:
    container_name: bigcity_mongodb
    image: mongo
    volumes:
      - /home/mongo/bigcity/data:/data/db
      - /home/mongo/bigcity/backups:/backups
    ports:
      - "27017:27017"
  bigcity_server:
    container_name: bigcity_server
    restart: on-failure
    build: .
    ports:
      - "9550:9550"
    links:
      - bigcity_mongodb:livingforestdb
      - bigcity_rabbitmq:livingforestmq