version: "3"
services:
  bigcity_rabbitmq:
    container_name: bigcity_rabbitmq
    image: "rabbitmq:management"
    environment:
      - RABBITMQ_DEFAULT_USER=jsm
      - RABBITMQ_DEFAULT_PASS=jsm
    ports:
      - "5672"
      - "15672"
  bigcity_mongodb:
    container_name: bigcity_mongodb
    image: mongo
    volumes:
      - /home/mongo/bigcity/data:/data/db
      - /home/mongo/bigcity/backups:/backups
    ports:
      - "28517:27017"
  bigcity_server:
    container_name: bigcity_server
    image: "node:16"
    environment:
      - RUNNING_MODE=rest
      - HTTPS=true
      - PORT=9550
      - MONGODB=mongodb://livingforestdb:27017/livingforest
      - MQ=amqp://jsm:jsm@livingforestmq
      - JWT_SECRET=MFswDQYJKoZIhvcNAQEBBQADSgAwRwJAamUL/pm3t5EZ
    entrypoint:
      - "sh"
      - "-c"
      - "npm install && node server.js"
    working_dir: "/usr/app/livingforest"
    ports:
      - "443:9550"
    volumes:
      - ".:/usr/app/livingforest"
      # Don't sync the node_modules directory back to the client.
      - "/usr/app/livingforest/node_modules"
    links:
      - bigcity_mongodb:livingforestdb
      - bigcity_rabbitmq:livingforestmq
